/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package helloJavaFXgroovyGradle;

public class App {
    public String getGreeting() {
        return "Hello mother fuckers.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
